### ISSUE TITLE
vue：Initialization error

### ISSUE THREAD

**Issue by Pigzhuyao** [css-doodle/css-doodle#122]
error  in ./node_modules/css-doodle/css-doodle.js

Module parse failed: Unexpected token (3725:31)
You may need an appropriate loader to handle this file type.
|         delete rules.frame;
|         rules['unit'] = 'none';
|         rules['stroke-width'] ??= .01;
|         rules['stroke'] ??= 'currentColor';
|         rules['fill'] ??= 'none';

**Comment by yuanchuan** [comment]
Have you tried to use the latest version of nodejs?

**Comment by yuanchuan** [comment]
https://caniuse.com/mdn-javascript_operators_nullish_coalescing_assignment
