### ISSUE TITLE
Consider writing tests

### ISSUE THREAD

**Issue by limonte** [css-doodle/css-doodle#18]
Congrats! AFAIK this is the first Web component in GitHub trending JS repos! :clap: :clap: :clap: 
 
`css-doodle` is sexy but absolutely not suitable for production use since there are **0 tests**.

Consider moving `css-doodle` on the next level, read/watch a tutorial on how to set up tests, e.g. https://www.youtube.com/watch?v=7r4xVDI2vho and start writing tests :)

Without tests, nobody in their right mind would use it.

From https://engineering.videoblocks.com/these-four-clean-code-tips-will-dramatically-improve-your-engineering-teams-productivity-b5bd121dd150

> If it isn’t tested, it’s broken

**Comment by yuanchuan** [comment]
Thanks for the advice!  Your links are helpful!
I'd write some tests, especially for the parser and generator whenever I've got time.

And any PRs are appreciated!

**Comment by limonte** [comment]
> And any PRs are appreciated!

Here you go: https://github.com/css-doodle/css-doodle/pull/19 :rocket:

**Comment by yuanchuan** [comment]
@limonte Thank you so much!

**Comment by fdrobidoux** [comment]
@limonte is right, altho for the time being, I cloned the `css-doodle.github.io` repo and replaced this line in the head section of `index.html` : 

```html
  <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/css-doodle/0.2.3/css-doodle.min.js"></script>-->
  <script src="../css-doodle/css-doodle.js"></script>
```
Knowing that I put both this repo's folder and the website's repo folder in the same root folder, and I make sure I `npm run build` everytime I make a change in the lib.
Not the best, and doesn't check every case, but it's doing the job for now.
