### ISSUE TITLE
repeating animations | question

### ISSUE THREAD

**Issue by diomed** [css-doodle/css-doodle#31]
hello

I wonder is it possible, and how - to animate - not just upon click or mousehover, 
but animate effects to repeat certain number of times, like 4 or 5,
but also, infinite number of times (constantly)

I'm especially interested in animating each of 3 elements  on the right in this pen:

https://codepen.io/yuanchuan/pen/zpvQvV

**Comment by yuanchuan** [comment]
Is this what you want?
https://codepen.io/yuanchuan/pen/BmvKqX

**Comment by diomed** [comment]
not quite.

lets just take that effect in the last one - bottom right one.
that is obviously not done by keyframes spin. spin is cool, however, 
that particle movement on hover isn't spin; I'm unsure what it is, but 
would like for it to repeat [infinite number of times]. - could you possibly
demo something like that.

**Comment by yuanchuan** [comment]
It can hardly be done with `css-doodle` if it couldn't be done with
keyframes. Otherwise you can try some JavaScript.
