### ISSUE TITLE
doodle中，:after/:before的content中无法使用自定义属性

### ISSUE THREAD

**Issue by HuShiyuFrontEnd** [css-doodle/css-doodle#33]
直接在css-doodle中写如下句法：
```
:before{
     content:var(--bar-value-string);
}
```
似乎是并不能有效果的，因为doodle会给这段代码加上`:nth-type-of`的伪类，然后变成这样：
```
.cell:nth-type-of(1):before{
     content:var(--bar-value-string);//伪类直接没了，就像没有content一样
}
```
但是，直接接在一般选择器后，这种写法是可行的，，例如：
.cell:before{
     content:var(--bar-value-string);//成功执行
}
这一问题依旧是我在写这个实验的时候发现的：
https://codepen.io/FOXhushiyu/pen/Eewrjq
当时自己试着注入了一段css，就可以在content里用自定义属性值了。。
当然，，与其用这种方法，或许提供更加符合doodle思想的方式，或许更加贴切一些也说不定。
------------------------------------------后面是一些闲话-------------------------------------------------
挺喜欢这个框架（我个人觉得可以叫框架了，感觉已经改变了我的开发思维）的，，最近在尝试用doodle实现各种基础的图表（柱图、饼图、折线图、热力图等等），虽然你的示例是拿来做图案的，但是看到这个框架第一眼就觉得，这是个做图表非常强力的工具，shadow dom完美解决了样式污染的可能，上手之快令人咂舌，而且不需要学canvas、svg（即使学了也没有直接css这么直观）。之前也用过echart和hightchart，如果用doodle做图表，有一个特别大的优势就是，可以直接用css修改样式（svg制图虽然也可以上css改一些东西，但是讲道理不够），这样，一个制作完成的图表，后期接手者不需要进行太多学习（学doodle真的很快，玩一下午就能入门）
加油！

**Comment by HuShiyuFrontEnd** [comment]
。。。才看到刚才的另一个问题的回复，那边提到的@get貌似就是在解决这个问题。
其实并不是说content不能使用自定义属性，只是说对前面额的选择器的写法有一些要求，，我那个图表示例，就成功把自定义属性塞到content里了。。
不过@get的方法似乎更为优雅，，或者你可以直接在doodle处理阶段，读取文本并分析的时候，抓取content后面的val，并将当前的rules里的里的自定义属性值，注入进来，有点，预处理器的味道。。

**Comment by yuanchuan** [comment]
> // 伪类直接没了，就像没有content一样

其实是有的，:before 在后面:

```
cell:nth-type-of(1):before {
  ...
}
```

content 能识别  `attr()` 和 `counter()`, 而使用 `var()` 内容里面要有引号才行，比如：

```css
--some-value: 100;
--another-value: '100';

::after {
  /*  not working */
  content: var(--some-value);

  /* ok */
  content: var(--another-value);
}
```

最新版本的 css-doodle  确实有 bug，把 `var(--some-value)` 直接变成了 `'var(--some-value')` . 待修复.


---------------


>挺喜欢这个框架（我个人觉得可以叫框架了，感觉已经改变了我的开发思维）的，最近在尝试用doodle实现各种基础的图表（柱图、饼图、折线图、热力图等等）

欢迎尝试 :)
