### ISSUE TITLE
Port to Vue.js

### ISSUE THREAD

**Issue by mvaneijgen** [css-doodle/css-doodle#36]
I was trying to use css-doodle in combination with Vue.js and tried to use [`v-model`](https://vuejs.org/v2/guide/forms.html) to bind data to specific parts of the doodle (let say the grid), but no luck with it. Vue.js is reactive, but css-doodle is probably not, so if I update data in my app, I need to manually `.update()` my doodle. So I put a watcher on my data element, but even that it doesn't like. 

[Over here I made a small test case](https://codepen.io/mvaneijgen/pen/gQXMoe). It should have drawn more horizontal elements based on the number in the input field (which you can update. You will see it `.update()`'s once and after that you get a blank canvas.

**Comment by yuanchuan** [comment]
Actually that's a bug in css-doodle. Please try v0.4.11 

https://unpkg.com/css-doodle@0.4.11/css-doodle.min.js

**Comment by mvaneijgen** [comment]
Cool that seems to work great https://codepen.io/mvaneijgen/pen/gQXMoe

Thanks!
