### ISSUE TITLE
Comment in the code will cause bug.

### ISSUE THREAD

**Issue by OfficialYoungX** [css-doodle/css-doodle#37]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/25839518/52763317-3d94e680-3056-11e9-9e5f-4ea9c207fddb.png">
当我在这里面添加了注释之后，图案就解析不出来了。打开之后一片空白。

**Comment by yuanchuan** [comment]
Please try `/* */`

**Comment by OfficialYoungX** [comment]
> Please try `/* */`

OK, it works! Thanks a lot.

**Comment by yuanchuan** [comment]
cool
