### ISSUE TITLE
Can't unfold @multiple() or @repeat() in @pick()

### ISSUE THREAD

**Issue by ibafly** [css-doodle/css-doodle#40]
Say an unusual use case:
``` css
 background: @pick-n(blue, @multiple(3, red));
```

Then we get one like:
``` css
background: red, red, red;
```

I don't know it's a bug or feature request or simply I used it in a wrong way.

**Comment by yuanchuan** [comment]
hmm... It treats `@multiple(3, red)` as a dependent value. Like this

```css
background: @pick-n(blue, (red, red, red));
```

But what you expected is probably this:

```css
background: @pick-n(blue, red, red, red);
```

Thanks for reporting. I think I should fix it.

**Comment by ibafly** [comment]
Yeah, opening the bracket is what I wanted.

Thank you for creating and maintaining this marvelous thing.
I won't miss your upcoming updates.

**Comment by yuanchuan** [comment]
Hi @ibafly, I'm planning to rewrite the whole parser/generator part. This issue will be fixed after that but it may take some time.

**Comment by ibafly** [comment]
Sounds huge.

Take your time and I'll still be a happy gazer.

**Comment by yuanchuan** [comment]
Added in 0.8.2
