### ISSUE TITLE
Making css-doodle responsive with media queries

### ISSUE THREAD

**Issue by monikawi** [css-doodle/css-doodle#41]
I've set up a background for my page using css-doodle. It looks fine when on full screen but because of the way my grid is set up, the shapes get smaller along with the screen and are completely invisible on split screen or when simulating mobile devices. I would like them to visually always be the same size.

Here's my CodePen demo: [link](https://codepen.io/anon/pen/jjVPoK)

Is it possible to use a media query for this or to make changes to my grid that will give me the desired effect?

**Comment by yuanchuan** [comment]
Hope you've fixed the problem :)

**Comment by j0b0sapi3n** [comment]
I can't seem to get media queries to work. The web inspector shows `@grid` as not being recognized. Are there more working examples of using css-doodle with media queries? I don't see any unfortunately.

**Comment by yuanchuan** [comment]
Hi @j0b0sapi3n , `@grid` inside media query is not supported right now and the grid can only be set once. Maybe will make to be dynamic in version 1.0

**Comment by ChrisDM1** [comment]
> Hi @j0b0sapi3n , `@grid` inside media query is not supported right now and the grid can only be set once. Maybe will make to be dynamic in version 1.0

I just did a litlle hack using two grids and flipping display from grid to none in the @media queries:
For what I wanted it didn't affect performance 

<div id="purpleDotsDesktop">
<css-doodle>
  <style>....
  </style>
 </css-doodle>
</div>

<div id="purpleDotsPhone">
<css-doodle>
  <style>....
  </style>
 </css-doodle>
</div>
 
@media screen and (max-width: 1000px) {
 #purpleDotsDesktop{
  display:none
 }
}

@media screen and (min-width: 1000px) `{`
 #purpleDotsPhone{
  display:none
 }
}
