### ISSUE TITLE
Distribute as JS modules

### ISSUE THREAD

**Issue by justinfagnani** [css-doodle/css-doodle#43]
It seems like css-doodle.js is packaged as UMD. While this is a good idea for a long time, I think the utility has passed, since all current browsers support modules (and web components!) natively. Bundlers support module format as input also.

Without being a JS module, there's no way to get the export CSSDoodle class except though a global. If css-doodle.js was a module, it could just be imported:

```js
import {CSSDoodle} from 'css-doodle';

// Maybe someone would extend it:
export class MyCSSDoodle extends CSSDoodle {}
```

**Comment by yuanchuan** [comment]
Thank you for the suggestion! Export the class outside might be useful. I'll add it in the future.

I've recently exposed a function instead of the component class, for integrating it into Observablehq more easily.

```js
import CSSDoodle from 'css-doodle';

// Would return a css-doodle instance.
let doodle = CSSDoodle`
  @grid: 10  / 320px;
`
document.body.appendChild(doodle);
```

**Comment by justinfagnani** [comment]
```ts
import CSSDoodle from 'css-doodle';
```

Does this work in browsers though? Last I checked standard import didn't work without a build.
