### ISSUE TITLE
Is it possible to @repeat a @stripe?

### ISSUE THREAD

**Issue by djmtype** [css-doodle/css-doodle#45]
How do we repeat a diagonal linear-gradient using this example?

```css
background-image: linear-gradient(45deg, @stripe(#ffffff, var(--transparent)));
```

This would be the long-hand css: 

```css
--transparent: rgba(255,255,255,0);
--stripes: linear-gradient(45deg, var(--transparent) 25%, #ffffff 25%, #ffffff 50%, var(--transparent) 50%, var(--transparent) 75%, #ffffff 75%, #ffffff 100%);

background-image: var(--stripes);
background-size: 10px 10px;
```

**Comment by yuanchuan** [comment]
If you understand your question correctly, what you may want to do is to repeat the color steps inside `@stripe` function:

```css
--transparent:  rgba(255, 255, 255, 0);

background: linear-gradient(
  45deg, 
  @stripes(
    var(--transparent), #ffffff, var(--transparent), #ffffff
  )
);
```

That's possible with `@m` and `@pn` functions, like so:

```css
--transparent:  rgba(255, 255, 255, 0);

background-image:  linear-gradient(
  45deg, 
  @stripes.@m4.@pn(var(--transparent), #fff)
);
```

Also see:

https://observablehq.com/@yuanchuan/stripe-function-in-css-doodle

**Comment by djmtype** [comment]
Beautiful! Thank you @yuanchuan. I didn't see your blog before. A great resource for `<css-doodle>`. [https://observablehq.com/@yuanchuan/](https://observablehq.com/@yuanchuan/)
