### ISSUE TITLE
Security vulnerability in trim coming from css-doodle

### ISSUE THREAD

**Issue by arobinson** [css-doodle/css-doodle#63]
A severe security vulnerability has been found in `trim@0.0.1`

`css-doodle` has a dependency on a dead project of `markdown-preview` that has the issue as one of its dependencies:

```
─┬ css-doodle@0.23.0
│ └─┬ markdown-preview@0.4.3
│   ├─┬ remark-parse@1.1.0
│   │ └── trim@0.0.1
│   └─┬ remark-rehype@1.3.0
│     └─┬ mdast-util-to-hast@2.5.0
│       └── trim@0.0.1
```

Example security issue:
https://snyk.io/test/npm/remark-parse/5.0.0

**Comment by yuanchuan** [comment]
Thanks for reporting.  Fixed in `v0.23.1`
