### ISSUE TITLE
Does it work with Canvas?

### ISSUE THREAD

**Issue by deadcoder0904** [css-doodle/css-doodle#66]
Specifically, I want to know if it can work with Konva JS (or react-konva)

If not, is there any way to do it?

Brilliant work 👏

**Comment by yuanchuan** [comment]
I suppose not, css-doodle can not be rendered in Canvas

**Comment by deadcoder0904** [comment]
oh cool, thought so too.

any workarounds or not possible in any way?

**Comment by Danny-Engelman** [comment]
Convert HTML to Canvas: https://html2canvas.hertzen.com/

**Comment by deadcoder0904** [comment]
the thing is i want to use it in combination with a project as a background image. i'm not sure how will i merge the canvas generated by doodle to my original canvas such that it blends in perfectly.

although, using doodles will take my app to the next-level indeed!

i was gonna use this library only just in case canvas isn't possible for a doodle project.
